import { Scholarship } from "./types";

export const MOCK_SCHOLARSHIPS: Scholarship[] = [
  {
    id: "gov-1",
    title: "Post-Matric Scholarship for SC Students",
    provider: "Ministry of Social Justice and Empowerment",
    providerType: "government",
    description: "Financial assistance for students from Scheduled Castes pursuing post-matric studies.",
    amount: "Full Tuition + Living Allowance",
    numericAmount: 500000,
    deadline: "2026-12-31",
    eligibility: "SC category students with family income < 2.5 LPA",
    maxIncome: 250000,
    qualifications: ["10th", "12th", "Undergraduate"],
    location: "India",
    applicationUrl: "https://scholarships.gov.in/",
    category: "Caste-based",
    rating: 4.5,
    reviewCount: 120
  },
  {
    id: "private-1",
    title: "Reliance Foundation Undergraduate Scholarship",
    provider: "Reliance Foundation",
    providerType: "private",
    description: "Supports meritorious students from underprivileged backgrounds for their undergraduate studies.",
    amount: "Up to 2,00,000 INR",
    numericAmount: 200000,
    deadline: "2026-10-15",
    eligibility: "Meritorious students from families with income < 6 LPA",
    maxIncome: 600000,
    qualifications: ["12th"],
    location: "India",
    applicationUrl: "https://www.reliancefoundation.org/scholarships",
    category: "Merit-based",
    rating: 4.8,
    reviewCount: 85
  },
  {
    id: "private-2",
    title: "TATA Scholarship for International Students",
    provider: "Tata Education and Development Trust",
    providerType: "private",
    description: "Scholarship for Indian students to study at Cornell University.",
    amount: "Full Tuition",
    numericAmount: 800000,
    deadline: "2026-01-01",
    eligibility: "Indian citizens admitted to Cornell for undergraduate programs",
    maxIncome: 1000000,
    qualifications: ["Undergraduate"],
    location: "Global",
    applicationUrl: "https://trusts.tata.com/",
    category: "International",
    rating: 4.9,
    reviewCount: 42
  },
  {
    id: "gov-2",
    title: "National Means-cum-Merit Scholarship",
    provider: "Department of School Education & Literacy",
    providerType: "government",
    description: "To award scholarships to meritorious students of economically weaker sections to arrest their drop out at class VIII.",
    amount: "12,000 INR per annum",
    numericAmount: 12000,
    deadline: "2026-11-30",
    eligibility: "Class IX students with family income < 3.5 LPA",
    maxIncome: 350000,
    qualifications: ["8th"],
    location: "India",
    applicationUrl: "https://scholarships.gov.in/",
    category: "Economically Weaker Section",
    rating: 4.2,
    reviewCount: 310
  }
];
